<?php 
require 'base.php';
?>
<?php require 'header.php'; ?>
<script src="http://maps.google.com/maps/api/js?sensor=false&libraries=geometry&v=3.7"></script>
<!--<script src="http://code.jquery.com/jquery-2.1.1.min.js"></script>-->
<script src="js/maplace-0.1.3.js"></script>
<div class="clearfix"></div>
<div class="carrusel"><!--<img src="img/fondo1.jpg" alt="" style="width:100%">--></div>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title>WOW SLIDER generated by WOWSlider.com</title>
	<meta http-equiv="content-type" content="text/html; charset=utf-8" />
	<meta name="keywords" content="WOW SLIDER, WOW Slider, jQuery Slider Step, jQuery Slider Set Value" />
	<meta name="description" content="WOW SLIDER created with WOW Slider, a free wizard program that helps you easily generate beautiful web slideshow" />
	<!-- Start WOWSlider.com HEAD section -->
	<link rel="stylesheet" type="text/css" href="engine1/style.css" media="screen" />
	<style type="text/css">a#vlb{display:none}</style>
	<script type="text/javascript" src="engine1/jquery.js"></script>
	<!-- End WOWSlider.com HEAD section -->
</head>
<body style="background-color:#ffffff">
	<!-- Start WOWSlider.com BODY section -->
	<div id="wowslider-container1">
	<div class="ws_images">
<a href="#"><img src="data1/images/Travesia.jpg" alt="Travesia" title="Travesia" id="wows0"/></a>
<a href="#"><img src="data1/images/actividades.jpg" alt="Actividades" title="Actividades" id="wows1"/></a>
<a href="#"><img src="data1/images/experiencias.jpg" alt="Experiencias" title="Experiencias" id="wows2"/></a>
<a href="#"><img src="data1/images/institucion.jpg" alt="Institucion" title="Institucion" id="wows3"/></a>
<a href="#"><img src="data1/images/lagos.jpg" alt="Lagos" title="Lagos" id="wows4"/></a>
<a href="#"><img src="data1/images/laguna_de_mucubaji.jpg" alt="Laguna de Mucubaji" title="Laguna de Mucubaji" id="wows5"/></a>
<a href="#"><img src="data1/images/paisajes.jpg" alt="Paisajes" title="Paisajes" id="wows6"/></a>
<a href="#"><img src="data1/images/picos.jpg" alt="Picos" title="Picos" id="wows7"/></a>
<a href="#"><img src="data1/images/roraima.jpg" alt="Roraima" title="Roraima" id="wows8"/></a>
<a href="#"><img src="data1/images/venezuela.jpg" alt="Venezuela" title="Venezuela" id="wows9"/></a>
</div>
<div class="ws_bullets"><div>
<a href="#wows0" title="."><img src="data1/tooltips/..jpg" alt="Travesia"/>1</a>
<a href="#wows1" title="Actividades"><img src="data1/tooltips/actividades.jpg" alt="Actividades"/>2</a>
<a href="#wows2" title="Experiencias"><img src="data1/tooltips/experiencias.jpg" alt="Experiencias"/>3</a>
<a href="#wows3" title="Institucion"><img src="data1/tooltips/institucion.jpg" alt="Institucion"/>4</a>
<a href="#wows4" title="Lagos"><img src="data1/tooltips/lagos.jpg" alt="Lagos"/>5</a>
<a href="#wows5" title="Laguna de Mucubaji"><img src="data1/tooltips/laguna_de_mucubaji.jpg" alt="Laguna de Mucubaji"/>6</a>
<a href="#wows6" title="Paisajes"><img src="data1/tooltips/paisajes.jpg" alt="Paisajes"/>7</a>
<a href="#wows7" title="Picos"><img src="data1/tooltips/picos.jpg" alt="Picos"/>8</a>
<a href="#wows8" title="Roraima"><img src="data1/tooltips/roraima.jpg" alt="Roraima"/>9</a>
<a href="#wows9" title="Venezuela"><img src="data1/tooltips/venezuela.jpg" alt="Venezuela"/>10</a>
</div></div>
<a style="display:none" href="http://wowslider.com">jQuery Slider Ie7 by WOWSlider.com v1.7</a>
	<div class="ws_shadow"></div>
	</div>
	<script type="text/javascript" src="engine1/script.js"></script>
	<!-- End WOWSlider.com BODY section -->
</body>
</html>
<div class="content">
	<div class="content_int">
		<h2><i class="fa fa-cubes" class="texto4"></i> Naturaleza en Venezuela</h2>
		<i class="texto4"><b>La naturaleza en Venezuela, un verdadero privilegio </b></i>  
		<br><br>
		<p style="text-indent:20px">Venezuela, ámbito natural de una enorme variedad de animales y plantas es una de las regiones con la mayor biodiversidad del mundo. La evolución de la flora y la fauna del país es el resultado de dos factores importantes: la variedad del paisaje, que facilitó el desarrollo de numerosos habitats distintos y la historia natural del continente. Después de estar geográficamente aislado por 70 millones de años, América del Sur se unió a América Central por un puente de tierra (ahora Panamá) que surgió del mar hace unos 3,5 millones de años. Gradualmente nuevas especies se propagaron desde Asia hasta América del Norte, Centroamérica y se infiltraron hacia América del Sur. Si bien este movimiento de vida animal y de plantas incrementó la biodiversidad del continente, produjo una gran competencia entre las especies y algunas de las cuales se extinguieron. Años más tarde, los períodos glaciares envolvieron América del Norte, partes de Europa y Asia mientras que América del Sur no sufrió ese fenómeno. En consecuencia, las especies que se habían establecido en el Continente sobrevivieron una era que fue testigo de la desaparición de muchas de ellas en la región norte del mundo.</p>

		<!--<p style="text-indent:20px">Animales y plantasEn la actualidad existen más de 250 especies de mamíferos en Venezuela, incluyendo el jaguar, el puma, el chigüire, el manatí, el mono aullador, la pereza y dos especies de delfines de agua dulce. También se encuentra en el país la nutria gigante, la más rara del mundo. La población de aves cuenta con más de 1200 especies, entre ellas el cóndor, la guacharaca, el flamenco, el pelícano, varias especies de loros, guacamayas y tucanes así como una rara especie nocturna, el guacharo. Los reptiles incluyen cinco especies distintas de caimanes, la iguana común, serpientes de cascabel, boas y la anaconda considerada como la serpiente más grande del mundo.</p>

		<p style="text-indent:20px">La flora venezolana es tan variada como su fauna, desde el simple cactus del desierto hasta las epífitas de la selva tropical. En las aisladas alturas de los tepuyes, montañas con cumbres tipo meseta de la Gran Sabana, crecen flores extraordinarias, algunas exclusivas de un solo plateau. Miles de especies de orquídeas florecen todo el año y existe una enorme variedad de árboles frutales. La flora tiene, en algunas regiones, significado cultural como la palma moriche, que crece en las zonas pantanosas del Delta del Orinoco donde se la conoce como árbol de la vida, pues juega un papel muy importante en la existencia de los indios Warao, suministrándoles alimento y materiales para su vida diaria. </p>-->
		<div class="clearfix"></div>
		<h2><i class="fa fa-gears"></i> ¿Qué quieres hacer en la naturaleza?</h2>
		<p>
			<ul class="actividades">
				<?php foreach($macti->lista() as $r): ?>
					<li>
						<a href="index_cont.php?page=<?php echo base64_encode('actividades') ?>&acti=<?php echo $r->acti_ide ?>">
						<img src="img/acti/<?php echo $r->acti_icono ?>" alt="" class="imgact" style="width:64px; height:64px"><br>
							<?php echo $r->acti_descrip ?>
						</a>
					</li>
				<?php endforeach; ?>
			</ul>
		</p>
		<!--<div class="clearfix"></div>
		<h2><i class="fa fa-list"></i> Espacio Naturales</h2>
		<div class="espaciosnat">
			<div class="espaciosnat-header">Parques Nacionales</div>
			<div class="espaciosnat-body">
				<?php foreach($mparq->listaLimit() as $ri=>$r): $n = $ri+2; ?>
					<div class="espaciosnat-img"><img src="img/<?php echo $n ?>.jpg" alt=""></div>
					
				<?php endforeach ?>
					<div class="clearfix"></div>
			</div>
		</div>-->
	</div>
</div>
<div class="sidebar">
	<div class="sideimg0" onclick="location.href='index_cont.php?page=<?php echo base64_encode('mapa') ?>'">
		<div class="sideblack0"></div>
		<img src="img/0.jpg" alt="" style="width:100%; height:140px;">
		<div class="texto0">¿Dónde ir?<br>Mapa Interactivo</div>
	</div>
	<div class="sideclima">
		<div id="tyt_wdgt_1442487465548" style="overflow:hidden;width:296px;height:400px;margin-left:.5px" data-options="color=verde&text=txt-tahoma&content=1111111&temp_unit=c&wind_unit=kmh"><script src="http://tiempoytemperatura.es/widgets/js/big-3days/3628473/tyt_wdgt_1442487465548/?v=0"></script></div>
	</div>
	<div class="sideimg1">
		<div class="sideblack1"></div>
		<img src="img/1.jpg" alt="" style="width:100%; height:130px">
		<div class="texto1">Naturaleza</div>
	</div>
	<?php foreach($mparq->listaLimit() as $ri=>$r): $n = $ri+2; ?>
	<!--<div class="sideimg<?php echo $n ?>"  onclick="modal('vst-page-mapabuscarparque2','parque=<?php echo $r->parq_ide ?>')">
		<!--<div class="sideblack<?php echo $n ?>"></div>
		<img src="img/<?php echo $n ?>.jpg" alt="" style="width:100%;height:150px">
		<div class="texto1"><?php echo $r->parq_nombre ?></div>-->
	<!--</div>
	<!--<div class="clearfix"></div>
	<!--<div class="sideimg3">
		<div class="sideblack3"></div>
		<img src="img/<?php #echo $n ?>.jpg" alt="" style="width:100%">
		<div class="texto1">Parque Nacional 2</div>
	</div>
	<div class="sideimg4">
		<div class="sideblack4"></div>
		<img src="img/<?php # echo $n ?>.jpg" alt="" style="width:100%;height:100px">
		<div class="texto1">Parque Nacional 3</div>
	</div>-->
	<?php endforeach ?>
</div>
<div class="clearfix"></div>	
<?php require 'footer.php'; ?>

